### ISSUE TITLE
IPv6 route table - pd-prefix showing "none"

### ISSUE THREAD

**Issue by rodrigo-sm2** [xebd/accel-ppp#87]
Hey, regards!

I'm using latest commit (2018-06-28) of accel-ppp on Ubuntu 18.04

When i'm runs accel in hwe (4.18) the route table for PD-Prefix (IPv6) show as "none":

ip -6 route show dev pppoe0
(/64 PREFIX) proto kernel metric 256 pref medium
**none** (PD /56 PREFIX) via fe80::200:0:0:0 metric 1024 pref medium
fe80::/64 proto kernel metric 256 pref medium

This did not occur when i'm run accel in 4.15 kernel:

(prefix /64) proto kernel metric 256 pref medium
(/56 prefix) via fe80::200:0:0:0 metric 1024 pref medium
fe80::/64 proto kernel metric 256 pref medium

with this I can not send the prefix via ospf. I think this is a bug.

Can solve this? 

(Sorry for my poor english!)

**Comment by DmitriyEshenko** [comment]
Hello, I think this issue was solved in commit 1f835bb6bb54cf186e549d58318090b988b6b93a try use current master tree

**Comment by rodrigo-sm2** [comment]
> Hello, I think this issue was solved in commit [1f835bb](https://github.com/xebd/accel-ppp/commit/1f835bb6bb54cf186e549d58318090b988b6b93a) try use current master tree. Anyway, if it isn't solve your problem, let me know.

Hey @DmitriyEshenko, thanks for answer!

I'm updated accel-ppp in this week. Anyway, i'm clone this repo again (master tree) for disengagement but the problem persists!

> ip -6 route show dev pppoe0
IP-TUNNEL::/64 proto kernel metric 256 pref medium
none IP-PREFIX:/56 via fe80::200:0:0:0 metric 1024 pref medium
fe80::/64 proto kernel metric 256 pref medium

I can confirm this issue in Debian 9 Stretch with backports repository kernel (4.19). In 4.9 kernel (in my production server), runs OK.

**Comment by rodrigo-sm2** [comment]
Confirmed: Applying #89 patch fix this issue! Many thanks, @themiron !
